### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4: invalid continuation byte

### ISSUE THREAD

**Issue by got2be** [Luzhnuy/attacker#2]
Двічі виникла помилка:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/got2be/apps/attacker/attack.py", line 37, in mainth
    data = loads(content)
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4: invalid continuation byte
```
Спробую самостійно подебажити, якщо ще спіймаю.

**Comment by Luzhnuy** [comment]
@got2be Дяукю велике, відфіксимо
